config/routes.rb
Rails.application.routes.draw do




 resources :attendees, only: [:new, :create]

  resources :events, only: [:index, :show] do
    resources :tickets, only: [:new, :create]
  end
    resource :ticket, only: [:show]


  root to: 'events#index'


  namespace :admin do
    resources :sessions, only: [:new, :create, :destroy]
    resources :admin, only: [:show]
    resources :events

    resources :attendees

    root to: "sessions#new"
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :ticket_types
  has_many :tickets
  has_many :attendees, through: :tickets

  accepts_nested_attributes_for :ticket_types
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::ApplicationController
  before_action :require_sign_in

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
    @event.ticket_types.build
  end

  def create
    @event = Event.create(event_params)
    create_ticket_types
    if @event.save
      flash[:notice] = "Event was created successfully."
      redirect_to admin_event_path(@event)
    else
      flash[:error] = "There was an error creating the event. Please try again."
      render new
    end

  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    @event.assign_attributes(event_params)
    #TODO need to enable ticket_type editing

    if @event.save
      flash[:notice] = "Event updated."
      redirect_to admin_event_path(@event)
    else
      flash[:error] = "There was an error saving the event. Please try again."
      render :edit
    end

  end


    def destroy
      @event = Event.find(params[:id])

      if @event.destroy
        flash[:notice] = "\"#{@event.name}\" was deleted successfully."
        redirect_to admin_events_path
      else
        flash[:error] = "There was an error deleting the event."
        render :show
      end
    end

  private

  def create_ticket_types
    params[:event][:ticket_types_attributes].values.each do |ticket_type_params|
      @event.ticket_types.create(ticket_type_params)
    end
  end


  def event_params
    params.require(:event).permit(:name, :date, :description)
  end

  def ticket_type_params
    params.require(:event).permit(ticket_types_attributes: [:level, :cost])
  end

  def require_sign_in
    unless current_user
      flash[:error] = "You must be logged in to do that"
      redirect_to new_admin_session_path
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/admin/events/_form.html.erb
<div class="form">
  <div class="form-group-columns">
  <%= form_for [:admin, @event]  do |f| %>
    <%= f.text_field :name, placeholder: "Name" %>
    <br/>
    <br/>
    <%= f.text_area :description, placeholder: "Description" %>
    <br/>
    <%= f.date_select(:date , :start_year => 2016) %>
    <br/>
    <%= f.fields_for :ticket_types do |ticket_type_form| %>
    <ul class="ticket-type-group">
      <li class="ticket-form">
        <%= ticket_type_form.label :type %>
        <%= ticket_type_form.text_field :level %>

        <%= ticket_type_form.label :price %>
        <%= ticket_type_form.number_field :cost %>
          <%# TODO Want to duplicate this to allow for multiple ticket_type param sets. %>
      </li>
    </ul>
    <span class="fa fa-plus-circle fa-2x ticket-form-add"></span>
    <br/>
    <% end %>
    <br/>
    <%= f.submit :save, class: "button" %>
  <% end %>
  </div>
</div>

app/views/admin/events/edit.html.haml
.container
  .row
    %h1 Edit
    = render partial: "form", locals: {event: @event}

app/views/admin/events/index.html.erb
  <div class="container">
      <button class="column third button form-button">
        <%= link_to "New Event", new_admin_event_path(@event) %>
      </button>
    <% @events.each do |event| %>
      <div class="event-item column third">
        <%=link_to image_tag("http://lorempixel.com/400/200/nightlife/5"), admin_event_path(event)%> <%# will use paperclip to add event.picture %>
        <h3>
          <%= link_to "#{event.name}", admin_event_path(event), class: "event-links" %>
        </h3>
      </div>
  <%# add breakpoints and change class from half to desired width %>
      <% end %>
  </div>

app/views/admin/events/new.html.haml
.container
  .row
    %h1 New Event
    = render partial: "form", locals: {event: @event}
     

app/views/admin/events/show.html.haml
.container
  %p
    Name: #{@event.name}
  %p
    Date: #{@event.date}
  %p
    Description: #{@event.description}
  %p
    Location: #{@event.location}
  %p
    Image:
  = link_to "Edit event", edit_admin_event_path(@event), class: "button"
  = link_to "Delete event", admin_event_path(@event), method: :delete, data: { confirm: 'Are you certain you want to delete this?' }, class: "button button-delete"