config/routes.rb
Rails.application.routes.draw do




 resources :attendees, only: [:new, :create]

  resources :events, only: [:index, :show] do
    resources :tickets, only: [:new, :create]
  end
    resource :ticket, only: [:show]


  root to: 'events#index'


  namespace :admin do
    resources :sessions, only: [:new, :create, :destroy]
    resources :admin, only: [:show]
    resources :events

    resources :attendees

    root to: "sessions#new"
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :ticket_types
  has_many :tickets
  has_many :attendees, through: :tickets

  accepts_nested_attributes_for :ticket_types
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::ApplicationController
  before_action :require_sign_in

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
    @event.ticket_types.build
  end

  def create
    @event = Event.create(event_params)
    create_ticket_types
    if @event.save
      flash[:notice] = "Event was created successfully."
      redirect_to admin_event_path(@event)
    else
      flash[:error] = "There was an error creating the event. Please try again."
      render new
    end

  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    @event.assign_attributes(event_params)
    #TODO need to enable ticket_type editing

    if @event.save
      flash[:notice] = "Event updated."
      redirect_to admin_event_path(@event)
    else
      flash[:error] = "There was an error saving the event. Please try again."
      render :edit
    end

  end


    def destroy
      @event = Event.find(params[:id])

      if @event.destroy
        flash[:notice] = "\"#{@event.name}\" was deleted successfully."
        redirect_to admin_events_path
      else
        flash[:error] = "There was an error deleting the event."
        render :show
      end
    end

  private

  def create_ticket_types
    params[:event][:ticket_types_attributes].values.each do |ticket_type_params|
      @event.ticket_types.create(ticket_type_params)
    end
  end


  def event_params
    params.require(:event).permit(:name, :date, :description)
  end

  def ticket_type_params
    params.require(:event).permit(ticket_types_attributes: [:level, :cost])
  end

  def require_sign_in
    unless current_user
      flash[:error] = "You must be logged in to do that"
      redirect_to new_admin_session_path
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_events.html.erb
<div class="container">
  <% @events.each do |event| %>
    <div class="event-item column third">
      <%=link_to image_tag("http://lorempixel.com/400/200/nightlife/5"), event_path(event)%> <%# will use paperclip to add event.picture %>
      <h3>
        <%= link_to "#{event.name}", event_path(event), class: "event-links" %>
      </h3>
    </div>
<%# add breakpoints and change class from half to desired width %>
    <% end %>
</div

app/views/events/_header.html.erb
<section class="header-content"><!-- hero content -->
    <h1 class="header-title">Get the party started!
        </br>
        </br>
            <%= link_to "Start Here", root_path, class: "button header-button" %>
    </h1>




</section>

app/views/events/index.html.erb
<%= render "header" %>
<div class="spacer"></div>
<%= render "events" %>

app/views/events/show.html.haml
.container
  .column.third
    %p
      Name: #{@event.name}
    %p
      Date: #{@event.date}
    %p
      Description: #{@event.description}
    %p
      Location: #{@event.location}
    %p
      Image:
      %br/
  .column.third
    .button-div
      = link_to "Get Ticket", new_event_ticket_path(@event), class: "button"
      %p
        Have a ticket? Get your info here.
        = form_tag ticket_path(@ticket), method: :get
        = text_field_tag "ticket[token]", nil, placeholder: "Confirmation Code"
        %br/
        = submit_tag "search"