config/routes.rb
Rails.application.routes.draw do




 resources :attendees, only: [:new, :create]

  resources :events, only: [:index, :show] do
    resources :tickets, only: [:new, :create]
  end
    resource :ticket, only: [:show]


  root to: 'events#index'


  namespace :admin do
    resources :sessions, only: [:new, :create, :destroy]
    resources :admin, only: [:show]
    resources :events

    resources :attendees

    root to: "sessions#new"
  end
end

app/models/attendee.rb
class Attendee < ActiveRecord::Base
  has_one :ticket

  validates :first_name, :last_name, :company, :email, presence: true
end

app/controllers/admin/attendees_controller.rb
class Admin::AttendeesController < Admin::ApplicationController
  before_action :require_sign_in

  def index
    @attendees = Attendee.all
  end

  def show
    @attendee = Attendee.find(params[:id])
  end

  def new
    @attendee = Attendee.new
  end

  def create
    @attendee = Attendee.create(attendee_params)

    if @attendee.save
      flash[:notice] = "Attendee was created successfully."
      redirect_to admin_attendee_path(@attendee)
    else
      flash[:error] = "There was an error creating the Attendee. Please try again."
      render new
    end

  end

  def edit
    @attendee = Attendee.find(params[:id])
  end

  def update
    @attendee = Attendee.find(params[:id])
    @attendee.assign_attributes(attendee_params)

    if @attendee.save
      flash[:notice] = "Attendee updated."
      redirect_to admin_attendee_path(@attendee)
    else
      flash[:error] = "There was an error saving the Attendee. Please try again."
      render :edit
    end

  end


  def destroy
    @attendee = Attendee.find(params[:id])

    if @attendee.destroy
      flash[:notice] = "\"#{@attendee.first_name} #{@attendee.last_name}\" was deleted successfully."
      redirect_to admin_attendees_path
    else
      flash[:error] = "There was an error deleting the Attendee."
      render :show
    end
  end

  private

  def attendee_params
    params.require(:attendee).permit(:first_name, :last_name, :email, :company)
  end

  def require_sign_in
    unless current_user
      flash[:error] = "You must be logged in to do that"
      redirect_to new_admin_session_path
    end
  end
end

app/helpers/admin/attendees_helper.rb
module Admin::AttendeesHelper
end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/views/admin/attendees/_form.html.haml
.form
  .form-group-columns
    = form_for [:admin, @attendee]  do |f|
      = f.text_field :first_name, placeholder: "First Name"
      = f.text_field :last_name, placeholder: "Last Name"
      = f.email_field :email, placeholder: "Email"
      = f.text_field :company, placeholder: "Company"
      = f.submit :save, class: "button"

app/views/admin/attendees/edit.html.haml
.container
  .row
    %h1 Edit
    = render partial: "form", locals: {attendee: @attendee}

app/views/admin/attendees/index.html.haml
.container
  .attendee-new
    = link_to "New Attendee", new_admin_attendee_path(@attendee), class: "button form-button"
  .attendee-list
    %ul
      - @attendees.each do |attendee|
        %li
          = "Date Purchased: #{attendee.created_at.strftime("%d %b. %Y")} -"
          = link_to "#{attendee.first_name} #{attendee.last_name}", admin_attendee_path(attendee)

app/views/admin/attendees/new.html.haml
.container
  .row
    %h1 New Attendee
    = render partial: "form", locals: {attendee: @attendee}

app/views/admin/attendees/show.html.haml
.container
  .column.two-thirds
    %p
      First Name: #{@attendee.first_name}
    %p
      Last Name: #{@attendee.last_name}
    %p
      Email: #{@attendee.email}
    %p
      Company: #{@attendee.company}

    %br/
      
    = link_to "Edit attendee", edit_admin_attendee_path(@attendee), class: "button"
    = link_to "Delete attendee", admin_attendee_path(@attendee), method: :delete, data: { confirm: 'Are you certain you want to delete this?' }, class: "button button-delete"


.ticket-attributes
  .column.third.flow-opposite
    %p
      Ticket Id: #{@attendee.ticket.id}
    %p
      Ticket Type Id: #{@attendee.ticket.ticket_type_id}
    %p
      Attendee ID: #{@attendee.ticket.attendee_id}
    %p
      Price Paid: #{@attendee.ticket.to_dollars(@attendee.ticket.price_paid)}
    %p
      Event Id: #{@attendee.ticket.event_id}
    %p
      Token: #{@attendee.ticket.token}
    %p
      Date Purchased: #{@attendee.created_at.strftime("%d %b. %Y")}