config/routes.rb
Rails.application.routes.draw do




 resources :attendees, only: [:new, :create]

  resources :events, only: [:index, :show] do
    resources :tickets, only: [:new, :create]
  end
    resource :ticket, only: [:show]


  root to: 'events#index'


  namespace :admin do
    resources :sessions, only: [:new, :create, :destroy]
    resources :admin, only: [:show]
    resources :events

    resources :attendees

    root to: "sessions#new"
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  has_secure_password
end

app/models/attendee.rb
class Attendee < ActiveRecord::Base
  has_one :ticket

  validates :first_name, :last_name, :company, :email, presence: true
end

app/models/create_charge.rb
class CreateCharge
  attr_reader :amount, :source

  def initialize(amount, source)
  #  raise if source.empty? || source.nil? 
    @amount = amount
    @source = source
  end

  def send_request_to_stripe
    @response = Stripe::Charge.create(
      amount: amount,
      currency: 'usd',
      source: source
    )
  end

  def completed?
    return false unless @response
    @response.status == "succeeded"
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :ticket_types
  has_many :tickets
  has_many :attendees, through: :tickets

  accepts_nested_attributes_for :ticket_types
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  has_one :ticket_type
  belongs_to :attendee
  belongs_to :event
  before_create :generate_token

  accepts_nested_attributes_for :attendee


  def to_dollars(num)
    "$"+"#{(num/100)}"
  end

  protected

  def generate_token
    loop do
      self.token = SecureRandom.base64(15)
      break unless Ticket.find_by(token: token)
    end
  end

end

app/models/ticket_type.rb
class TicketType < ActiveRecord::Base
  belongs_to :event

  def to_dollars(num)
    "$"+"#{(num/100)}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    admin = Admin.find_by(email: params[:session][:email].downcase)

    if admin && admin.authenticate(params[:session][:password])
      create_session(admin)
      flash[:notice] = "Welcome back"
      redirect_to admin_path(admin)
    else
      flash.now[:alert] = "invalid email/password combination"
      render :new
    end
  end

  def destroy
    destroy_session(current_user)
    flash[:notice] = "Successfully signed out."
    redirect_to root_path
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def new
    @event = Event.find(params[:event_id])
    @ticket = Ticket.new
  end

  def create

    @event = Event.find(params[:event_id])
      charge = CreateCharge.new(ticket_type.cost, params[:stripe_charge])
      charge.send_request_to_stripe

      if charge.completed?
        @ticket = @event.tickets.create(ticket_params)
        redirect_to @event
        flash[:notice] = "#{@ticket.token} is your confirmation code! Copy and Paste Below."
      else
        flash.now[:error] = "Something went wrong. Please try again or use another card." #will stub out different error message possibilities
      end
  end

  def show
    @ticket ||= Ticket.find_by(token: params[:ticket][:token])
  end

  def success
    @ticket = Ticket.find(params[:id])
  end

  private

  def ticket_type
    @ticket_type ||= TicketType.find(params[:ticket][:ticket_type_id])
  end

  def ticket_params
    params
      .require(:ticket)
      .permit(:ticket_type_id, :attendee_id, :event_id, :price_paid, attendee_attributes: [:first_name, :last_name, :email, :company])
      .merge(ticket_type_id: ticket_type.id, price_paid: ticket_type.cost)
  end
end

app/helpers/admin/admin_helper.rb
module Admin::AdminHelper
  def current_user
    Admin.find_by(id: session[:admin_id])
  end
end

app/helpers/admin/attendees_helper.rb
module Admin::AttendeesHelper
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/ticket_types_helper.rb
module TicketTypesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/admin/admin/show.html.erb
<div class="space"></div>
<div class="container">
  <div class="dash-links-set">
    <div class="dash-link column third">
      <div class="round-button center">
        <div class="round-button-circle">
          <%= link_to "Events", admin_events_path %>
        </div>
      </div>
    </div>
    <div class="dash-link column third">
      <div class="round-button center">
        <div class="round-button-circle">
          <%= link_to "Attendees", admin_attendees_path %>
        </div>
      </div>
    </div>
    <div class="dash-link column third">
      <div class="round-button center">
        <div class="round-button-circle">
          <a href="#">Extra Link</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_admin_nav.html.haml
%nav.navbar
  %a.logo{:href => "#"}
  = link_to image_tag("ERlogo.png"), root_path
  .links-container
    %a.navbar-link{:href => admin_admin_path(current_user)} Dashboard

app/views/layouts/_nav.html.haml
%nav.navbar
  %a.logo{:href => "#"}
  = link_to image_tag("ERlogo.png"), root_path
  .links-container
    %a.navbar-link{:href => root_path} Event Registration, Inc.

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %title EventRegistration
    = stylesheet_link_tag    'admin/base', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %link{:href => "http://fonts.googleapis.com/css?family=Open+Sans:400,800,600,700,300", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css", :rel => "stylesheet", :type => "text/css"}/
  %body
    = render 'layouts/shared/flash'
    = render 'layouts/admin_nav' unless @disable_nav
    .spacer
    = yield

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title EventRegistration
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %link{:href => "http://fonts.googleapis.com/css?family=Open+Sans:400,800,600,700,300", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css", :rel => "stylesheet", :type => "text/css"}/
  %body
    = render 'layouts/shared/flash'
    = render 'layouts/nav'
    = yield

app/views/layouts/shared/_flash.html.haml
.flash
  - if flash[:notice]
    .alert.alert-success
      %button.close{"data-dismiss" => "alert", :type => "button"} ×
      = flash[:notice]
  - elsif flash[:error]
    .alert.alert-danger
      %button.close{"data-dismiss" => "alert", :type => "button"} ×
      = flash[:error]
  - elsif flash[:alert]
    .alert.alert-warning
      %button.close{"data-dismiss" => "alert", :type => "button"} ×
      = flash[:alert]